{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7f960507-3350-4796-8ab2-d50df2acef7b",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''Q1. What is an Exception in python? Write the difference between Exceptions and Syntax errors.'''\n",
    "\n",
    "#Ans..\n",
    "'''An Exception in Python is an event that occurs during the execution of a program, which disrupts the normal\n",
    "flow of the program's instructions. When an exception occurs, the program stops executing further \n",
    "instructions in the try block and jumps to the appropriate exception handler.\n",
    "\n",
    "1. Syntax errors: These errors occur when the Python interpreter encounters a statement that violates the \n",
    "rules of the Python language. It usually happens due to incorrect syntax, such as missing parentheses,\n",
    "misspelled keywords, or incorrect indentation.\n",
    "\n",
    "2. Exceptions: These errors occur during the execution of a program after it has successfully passed the \n",
    "parsing phase. Exceptions can happen due to various reasons, such as invalid user input, division by zero,\n",
    "or accessing a non-existent file. '''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b47ab603-0fc4-44be-a122-68dadf7a8a70",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''Q2.What happens when an exception is not handled?Explain with an example.'''\n",
    "\n",
    "#Ans..\n",
    "'''When an exception is not handled, it leads to the termination of the program and an error message \n",
    "is displayed, indicating the type of exception that occurred and the line of code where it occurred.\n",
    "\n",
    "Here's an example:'''\n",
    "\n",
    "a = 10\n",
    "b = 0\n",
    "result = a/b\n",
    "print(\"Result:\", result)\n",
    "\n",
    "'''This will raise a ZeroDivisionError exception since dividing by zero is mathematically undefined'''\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ff65a659-c77e-4102-a5b1-a0116dc8d695",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''Q3. Which python statements are used to catch and handle exceptions? Explain with an example.'''\n",
    "\n",
    "#Ans..\n",
    "\n",
    "'''The Python statements used to catch and handle exceptions are try and except. \n",
    "\n",
    "The try block is used to enclose the code that may raise an exception. If an exception occurs within the\n",
    "try block, it is caught and the code within the corresponding except block is executed.\n",
    "\n",
    "For example:'''\n",
    "\n",
    "a = 10\n",
    "b = 0\n",
    "\n",
    "try:\n",
    "    result = a / b\n",
    "    print(\"Result:\", result)\n",
    "except ZeroDivisionError:\n",
    "    print(\"Error: Cannot divide by zero.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d1ad1b57-81a8-48e7-be82-2c47362f217a",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''Q4. Explain with an example:\n",
    "a. try and else\n",
    "b. finally\n",
    "c. else'''\n",
    "\n",
    "#Ans...\n",
    "\n",
    "'''The else block is used in conjunction with the try block to specify a block of code that should be \n",
    "executed if no exceptions are raised within the try block.\n",
    "\n",
    "for example:'''\n",
    "\n",
    "x = 10\n",
    "y = 5\n",
    "\n",
    "try:\n",
    "    result = x / y\n",
    "except ZeroDivisionError:\n",
    "    print(\"Error: Cannot divide by zero.\")\n",
    "else:\n",
    "    print(\"Result:\", result)\n",
    "\n",
    "    \n",
    "'''The finally block is used to specify a block of code that should be executed regardless of whether an\n",
    "exception was raised or not.\n",
    "\n",
    "for example:'''\n",
    "\n",
    "python\n",
    "a = 10\n",
    "b = 0\n",
    "\n",
    "try:\n",
    "    result = a / b\n",
    "    print(\"Result:\", result)\n",
    "except ZeroDivisionError:\n",
    "    print(\"Error: Cannot divide by zero.\")\n",
    "finally:\n",
    "    print(\"This code will always be executed.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a1d299ec-f59f-4c09-b5d4-8489bd3d3a1d",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''Q5. What are Custom Exceptions in python? Why do we need Custom Exceptions? Explain with an example.'''\n",
    "\n",
    "#Ans..\n",
    "\n",
    "'''Custom exceptions in Python are user-defined exceptions that allow developers to create their own specific \n",
    "exception types. They can be used to handle specific error conditions that are not covered by the built-in\n",
    "exceptions in Python.\n",
    "\n",
    "There are a few reasons why we may need custom exceptions:\n",
    "\n",
    "1. Specific Error Handling: Custom exceptions allow us to handle specific error conditions in a more \n",
    "meaningful way.\n",
    "\n",
    "2. Code Organization: By creating custom exceptions, we can organize our code and make it more readable. \n",
    "Instead of using generic exceptions like ValueError or TypeError, we can create custom exceptions with\n",
    "meaningful names that reflect the specific error condition being handled.\n",
    "\n",
    "3. Code Reusability: Custom exceptions can be reused across multiple projects or modules. Once defined, \n",
    "they can be imported and used wherever needed, providing consistency in error handling.\n",
    "\n",
    "For example:'''\n",
    "\n",
    "class InsufficientFundsError(Exception):\n",
    "    def __init__(self, amount, balance):\n",
    "        self.amount = amount\n",
    "        self.balance = balance\n",
    "\n",
    "    def __str__(self):\n",
    "        return f\"Insufficient funds. Available balance: {self.balance}, requested amount: {self.amount}\"\n",
    "\n",
    "def withdraw(amount, balance):\n",
    "    if amount > balance:\n",
    "        raise InsufficientFundsError(amount, balance)\n",
    "    else:\n",
    "        \n",
    "        pass\n",
    "\n",
    "try:\n",
    "    withdraw(1000, 500)\n",
    "except InsufficientFundsError as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e3b5d66a-10db-4f6a-84ed-9101d9630268",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''Q6. Create a custom exception class. Use this class to handle an exception.'''\n",
    "\n",
    "#Ans..\n",
    "\n",
    "class CustomException(Exception):\n",
    "    def __init__(self, message):\n",
    "        self.message = message\n",
    "\n",
    "    def __str__(self):\n",
    "        return f\"Custom Exception: {self.message}\"\n",
    "\n",
    "def divide_numbers(a, b):\n",
    "    if b == 0:\n",
    "        raise CustomException(\"Cannot divide by zero\")\n",
    "    else:\n",
    "        return a / b\n",
    "\n",
    "try:\n",
    "    result = divide_numbers(10, 0)\n",
    "except CustomException as e:\n",
    "    print(e)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
